services:
  postgres:
    container_name: postgres
    image: postgres:12
    environment:
    - POSTGRES_DB=${DATABASE_NAME-postgres}
    - POSTGRES_USER=${DATABASE_USER-postgres}
    - POSTGRES_PASSWORD=${DATABASE_PASSWORD-postgres}
    ports:
      - "5432:5432"
    volumes:
      - ./devel/postgresql/data:/var/lib/${DATABASE_DATA_DIR-postgresql}/data:Z
      - ./devel/postgresql/init:/docker-entrypoint-initdb.d:Z
    command:
      # This command give more precise control over the parameter settings
      # Included are loading the pg_stat_statements lib
      # as well as autovacuum settings that are designed to make more efficient
      # use of the autovacuum processes
      # The pg_init mount is still needed to enable the necesary extensions.
      - postgres
      - -c
      - max_connections=1710
      - -c
      - shared_preload_libraries=pg_stat_statements
      - -c
      - autovacuum_max_workers=8
      - -c
      - autovacuum_vacuum_cost_limit=4800
      - -c
      - autovacuum_vacuum_cost_delay=10
      - -c
      - pg_stat_statements.max=2000
      - -c
      - pg_stat_statements.save=off
      - -c
      - pg_stat_statements.track_utility=off
      - -c
      - track_activity_query_size=2048
      - -c
      - track_functions=pl
      - -c
      - log_min_error_statement=error
      - -c
      - log_min_duration_statement=2000
      - -c
      - logging_collector=on
      # Log line prefix (this matches RDS):
      #   %t = timestamp without milliseconds
      #   %r = remote host name/ip and remote port
      #   %u = user name
      #   %d = database name
      #   %p = process id (postgres backend)
      - -c
      - "log_line_prefix=%t:%r:%u@%d:[%p]:"
      # Change mod to all to log all statements including SELECT
      - -c
      - log_statement=mod
      # Uncomment this to get duration information on all statements, whether
      # the statement is logged or not.
      # - -c
      # - log_duration=true
      # Uncomment this parameter to get statistics details in the logs
      # This will really increase the log file size
      # - -c
      # - log_statement_stats=true
      #
  solr:
    container_name: solr
    image: solr:latest
    hostname: solr1
    ports:
      - 8983:8983
    environment:
      SOLR_HOST: solr1
    command:
      - solr-create
      - -c devel
      - -d /opt/solr/server/solr/configsets
    volumes:
      - ./devel/solr/data:/var/solr:Z
      - ./devel/solr/configsets:/opt/solr/server/solr/configsets:Z
    depends_on:
      - postgresql
      - zookeeper
  # if you want to run a cluster, copy the zookeeper block and update the names and ZOO_SERVERS list
  zookeeper:
    image: zookeeper:latest
    restart: always
    hostname: zookeeper1
    ports:
      - 2181:2181
    environment:
      ZOO_SERVER_ID: 1
      # ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181
      ZOO_LOG_LEVEL: DEBUG
      ZOO_LOG4J_PROP: "INFO,ROLLINGFILE"
      ALLOW_ANONYMOUS_LOGIN: true
    volumes:
      - ./devel/zookeeper/data:/data:Z
      - ./devel/zookeeper/datalog:/datalog:Z
      - ./devel/zookeeper/logs:/logs:Z
      - ./devel/zookeeper/zoo.cfg:/conf/zoo.cfg:Z
