---
# Title: create the Ansible playbook for Red Hat SSO in OpenShift
# Mission: create the Ansible playbook for Red Hat SSO in OpenShift
# Milestone: Automate SSO Deployment
# Column: Automate SSO Deployment

- name: Install the Red Hat SSO pod on OpenShift
  hosts: localhost
  connection: local
  vars_files:
    - /usr/local/src/opendatapolicing-ansible/vaults/{{ lookup('env', 'VAULT_ID') }}/vault
  roles: 
    - redhat_sso_openshift
